-- MySQL Script generated by MySQL Workbench
-- seg 17 jun 2024 18:25:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quantum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quantum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quantum` ;
USE `quantum` ;

-- -----------------------------------------------------
-- Table `quantum`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`cliente` ;

CREATE TABLE IF NOT EXISTS `quantum`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`tipo_contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`tipo_contato` ;

CREATE TABLE IF NOT EXISTS `quantum`.`tipo_contato` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('ENDERECO_RES', 'ENDERECO_COM', 'TELEFONE_FIXO', 'CELULAR') NOT NULL,
  `nome` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`cliente_contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`cliente_contato` ;

CREATE TABLE IF NOT EXISTS `quantum`.`cliente_contato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_tipo_contato` TINYINT UNSIGNED NOT NULL,
  `contato` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_contato_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `cliente_contato_tipo_contato_idx` (`id_tipo_contato` ASC) VISIBLE,
  CONSTRAINT `cliente_contato_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `quantum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_contato_tipo_contato`
    FOREIGN KEY (`id_tipo_contato`)
    REFERENCES `quantum`.`tipo_contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`cliente_foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`cliente_foto` ;

CREATE TABLE IF NOT EXISTS `quantum`.`cliente_foto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `url_foto` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_foto_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `cliente_foto_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `quantum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`cliente_assinatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`cliente_assinatura` ;

CREATE TABLE IF NOT EXISTS `quantum`.`cliente_assinatura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `certificado` TEXT NOT NULL,
  `data_expiracao` TIMESTAMP NOT NULL,
  `data_criacao` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP()',
  PRIMARY KEY (`id`),
  INDEX `cliente_assinatura_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `cliente_assinatura_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `quantum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`tipo_transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`tipo_transacao` ;

CREATE TABLE IF NOT EXISTS `quantum`.`tipo_transacao` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('DOC', 'TED', 'PIX') NOT NULL,
  `nome` VARCHAR(8) NOT NULL,
  `ativo` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`usuario_externo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`usuario_externo` ;

CREATE TABLE IF NOT EXISTS `quantum`.`usuario_externo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`conta_bancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`conta_bancaria` ;

CREATE TABLE IF NOT EXISTS `quantum`.`conta_bancaria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NULL,
  `id_usuario_externo` INT UNSIGNED NULL,
  `banco` SMALLINT UNSIGNED NOT NULL,
  `tipo_conta` ENUM('CC', 'CP') NOT NULL,
  `conta` INT UNSIGNED NOT NULL,
  `conta_digito` TINYINT UNSIGNED NOT NULL,
  `agencia` SMALLINT UNSIGNED NOT NULL,
  `agencia_digito` TINYINT UNSIGNED NOT NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `conta_bancaria_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `conta_bancaria_usuario_externo_idx` (`id_usuario_externo` ASC) VISIBLE,
  CONSTRAINT `conta_bancaria_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `quantum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conta_bancaria_usuario_externo`
    FOREIGN KEY (`id_usuario_externo`)
    REFERENCES `quantum`.`usuario_externo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`transacao` ;

CREATE TABLE IF NOT EXISTS `quantum`.`transacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_transacao` TINYINT UNSIGNED NOT NULL,
  `id_conta_debito` INT UNSIGNED NOT NULL,
  `id_conta_credito` INT UNSIGNED NOT NULL,
  `valor` DECIMAL(9,2) UNSIGNED NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `status` ENUM('EM_ANDAMENTO', 'SUCESSO', 'ERRO') NOT NULL DEFAULT 'EM_ANDAMENTO',
  `geolocalizacao_latitude` DOUBLE NOT NULL,
  `geolocalizacao_longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `transacao_conta_bancaria_debito_idx` (`id_conta_debito` ASC) VISIBLE,
  INDEX `transacao_conta_bancaria_credito_idx` (`id_conta_credito` ASC) VISIBLE,
  INDEX `transacao_tipo_transacao_idx` (`id_tipo_transacao` ASC) VISIBLE,
  CONSTRAINT `transacao_conta_bancaria_debito`
    FOREIGN KEY (`id_conta_debito`)
    REFERENCES `quantum`.`conta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transacao_conta_bancaria_credito`
    FOREIGN KEY (`id_conta_credito`)
    REFERENCES `quantum`.`conta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transacao_tipo_transacao`
    FOREIGN KEY (`id_tipo_transacao`)
    REFERENCES `quantum`.`tipo_transacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`produto` ;

CREATE TABLE IF NOT EXISTS `quantum`.`produto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `resumo` TEXT NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`recomendacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`recomendacao` ;

CREATE TABLE IF NOT EXISTS `quantum`.`recomendacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_conta_bancaria` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `conta_produto_un` (`id_conta_bancaria` ASC, `id_produto` ASC) VISIBLE,
  INDEX `recomendacao_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `recomendacao_conta_bancaria`
    FOREIGN KEY (`id_conta_bancaria`)
    REFERENCES `quantum`.`conta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recomendacao_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `quantum`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`transacao_analise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`transacao_analise` ;

CREATE TABLE IF NOT EXISTS `quantum`.`transacao_analise` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `dia` DATE NOT NULL,
  `total` DECIMAL(15,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `transacao_analise_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `transacao_analise_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `quantum`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`portfolio` ;

CREATE TABLE IF NOT EXISTS `quantum`.`portfolio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `renda_minima` DECIMAL(9,2) UNSIGNED NOT NULL,
  `renda_maxima` DECIMAL(9,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`portfolio_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`portfolio_produto` ;

CREATE TABLE IF NOT EXISTS `quantum`.`portfolio_produto` (
  `id_portfolio` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_portfolio`, `id_produto`),
  INDEX `portfolio_produto_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `portfolio_produto_portfolio`
    FOREIGN KEY (`id_portfolio`)
    REFERENCES `quantum`.`portfolio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `portfolio_produto_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `quantum`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`contratacao_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`contratacao_produto` ;

CREATE TABLE IF NOT EXISTS `quantum`.`contratacao_produto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_conta_bancaria` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `geolocalizacao_latitude` DOUBLE NOT NULL,
  `geolocalizacao_longitude` DOUBLE NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `contratacao_produto_conta_bancaria_idx` (`id_conta_bancaria` ASC) VISIBLE,
  INDEX `contratacao_produto_produto_idx` (`id_produto` ASC) VISIBLE,
  UNIQUE INDEX `conta_bancaria_produto` (`id_conta_bancaria` ASC, `id_produto` ASC) VISIBLE,
  CONSTRAINT `contratacao_produto_conta_bancaria`
    FOREIGN KEY (`id_conta_bancaria`)
    REFERENCES `quantum`.`conta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacao_produto_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `quantum`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantum`.`recomendacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quantum`.`recomendacao` ;

CREATE TABLE IF NOT EXISTS `quantum`.`recomendacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_conta_bancaria` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `conta_produto_un` (`id_conta_bancaria` ASC, `id_produto` ASC) VISIBLE,
  INDEX `recomendacao_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `recomendacao_conta_bancaria`
    FOREIGN KEY (`id_conta_bancaria`)
    REFERENCES `quantum`.`conta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recomendacao_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `quantum`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `quantum`.`tipo_contato`
-- -----------------------------------------------------
START TRANSACTION;
USE `quantum`;
INSERT INTO `quantum`.`tipo_contato` (`id`, `tipo`, `nome`) VALUES (1, 'ENDERECO_RES', 'Endereço Residencial');
INSERT INTO `quantum`.`tipo_contato` (`id`, `tipo`, `nome`) VALUES (2, 'ENDERECO_COM', 'Endereço Comercial');
INSERT INTO `quantum`.`tipo_contato` (`id`, `tipo`, `nome`) VALUES (3, 'TELEFONE', 'Telefone');

COMMIT;


-- -----------------------------------------------------
-- Data for table `quantum`.`tipo_transacao`
-- -----------------------------------------------------
START TRANSACTION;
USE `quantum`;
INSERT INTO `quantum`.`tipo_transacao` (`id`, `tipo`, `nome`, `ativo`) VALUES (1, 'DOC', 'Doc', '1');
INSERT INTO `quantum`.`tipo_transacao` (`id`, `tipo`, `nome`, `ativo`) VALUES (2, 'TED', 'TED', '1');
INSERT INTO `quantum`.`tipo_transacao` (`id`, `tipo`, `nome`, `ativo`) VALUES (3, 'PIX', 'Pix', '1');

COMMIT;

